### ISSUE TITLE
Docker for webhosting 

### ISSUE THREAD

**Issue by curtisdelicata** [liberu-control-panel/control-panel-laravel#6]
https://github.com/evertramos/nginx-proxy-automation

**Comment by curtisdelicata** [comment]
Creating a Docker Compose setup for automatic provisioning of websites with Nginx and Let's Encrypt (using Certbot) involves several steps. The goal is to have separate containers for each virtual host, managed by Nginx, with SSL certificates automatically provisioned and renewed by Certbot. Here’s a step-by-step guide to achieve this:

### Step 1: Create a Directory Structure

Create a directory for your project and navigate into it:

```bash
mkdir nginx-certbot-setup
cd nginx-certbot-setup
```

### Step 2: Create Docker Compose File

Create a `docker-compose.yml` file with the following content:

```yaml
version: '3.8'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:ro

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs:rw
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html

  web1:
    image: nginx:latest
    container_name: web1
    environment:
      - VIRTUAL_HOST=example.com,www.example.com
      - LETSENCRYPT_HOST=example.com,www.example.com
      - LETSENCRYPT_EMAIL=your-email@example.com
    volumes:
      - ./web1/html:/usr/share/nginx/html
      - ./web1/vhost.d:/etc/nginx/conf.d

  web2:
    image: nginx:latest
    container_name: web2
    environment:
      - VIRTUAL_HOST=example2.com,www.example2.com
      - LETSENCRYPT_HOST=example2.com,www.example2.com
      - LETSENCRYPT_EMAIL=your-email@example.com
    volumes:
      - ./web2/html:/usr/share/nginx/html
      - ./web2/vhost.d:/etc/nginx/conf.d

networks:
  default:
    external:
      name: nginx-proxy
```

### Step 3: Create Network

Create a Docker network to be used by the containers:

```bash
docker network create nginx-proxy
```

### Step 4: Create Directory Structure for Web Content

Create directories for the web content and configuration for each website:

```bash
mkdir -p nginx/vhost.d
mkdir -p nginx/html
mkdir -p nginx/certs

mkdir -p web1/html
mkdir -p web1/vhost.d

mkdir -p web2/html
mkdir -p web2/vhost.d
```

### Step 5: Add Sample Web Content

Add some sample content to the `html` directories:

```bash
echo "<h1>Welcome to example.com</h1>" > web1/html/index.html
echo "<h1>Welcome to example2.com</h1>" > web2/html/index.html
```

### Step 6: Start the Docker Compose Setup

Start the Docker Compose setup:

```bash
docker-compose up -d
```

### Explanation

1. **nginx-proxy**: This service uses the `jwilder/nginx-proxy` image, which automatically sets up a reverse proxy for any containers with the `VIRTUAL_HOST` environment variable.

2. **nginx-proxy-letsencrypt**: This service uses the `jrcs/letsencrypt-nginx-proxy-companion` image, which works alongside `nginx-proxy` to automatically obtain and renew Let's Encrypt SSL certificates.

3. **web1 and web2**: These services are example web servers using the official Nginx image. They are configured with environment variables to specify their virtual hosts and Let's Encrypt settings.

4. **Volumes**:
   - `/var/run/docker.sock:/tmp/docker.sock:ro`: Allows `nginx-proxy` and the Let's Encrypt companion to interact with the Docker daemon.
   - `./nginx/vhost.d`, `./nginx/html`, and `./nginx/certs`: Shared volumes for configuration, web content, and SSL certificates.

5. **Network**: The `nginx-proxy` network allows containers to communicate with each other. It is created externally to ensure persistence.

### Conclusion

This setup provides a scalable way to automatically provision websites with Nginx and Let's Encrypt. You can add more web services by following the pattern used for `web1` and `web2`, each with its own unique `VIRTUAL_HOST` and `LETSENCRYPT_HOST` environment variables.

**Comment by curtisdelicata** [comment]
To create a Docker Compose setup for automatic provisioning of websites with Nginx and Let's Encrypt (using Certbot) and support virtual hosts in separate containers defined in their own Docker Compose files, you can use a combination of `nginx-proxy` and `letsencrypt-nginx-proxy-companion`. Here's how you can achieve this:

### Step 1: Create the Main `docker-compose.yml`

First, create the main `docker-compose.yml` file that sets up the `nginx-proxy` and `letsencrypt-nginx-proxy-companion` services.

Create a directory for your main setup and navigate into it:

```bash
mkdir nginx-proxy-setup
cd nginx-proxy-setup
```

Create a `docker-compose.yml` file with the following content:

```yaml
version: '3.8'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/conf.d:/etc/nginx/conf.d

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs:rw
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html

networks:
  default:
    external:
      name: nginx-proxy
```

### Step 2: Create a Network

Create a Docker network to be used by the containers:

```bash
docker network create nginx-proxy
```

### Step 3: Create Directory Structure

Create directories for shared volumes:

```bash
mkdir -p nginx/vhost.d
mkdir -p nginx/html
mkdir -p nginx/certs
mkdir -p nginx/conf.d
```

### Step 4: Start the Main Setup

Start the Docker Compose setup for `nginx-proxy` and `letsencrypt-nginx-proxy-companion`:

```bash
docker-compose up -d
```

### Step 5: Create Separate Docker Compose Files for Each Website

Now, create separate Docker Compose files for each website. Each website will have its own directory with a `docker-compose.yml` file.

#### Example for `website1`

1. Create a directory for `website1`:

    ```bash
    mkdir -p ../website1
    cd ../website1
    ```

2. Create a `docker-compose.yml` file for `website1` with the following content:

    ```yaml
    version: '3.8'

    services:
      web1:
        image: nginx:latest
        container_name: web1
        environment:
          - VIRTUAL_HOST=example.com,www.example.com
          - LETSENCRYPT_HOST=example.com,www.example.com
          - LETSENCRYPT_EMAIL=your-email@example.com
        volumes:
          - ./html:/usr/share/nginx/html
          - ./vhost.d:/etc/nginx/conf.d
        networks:
          - nginx-proxy

    networks:
      nginx-proxy:
        external:
          name: nginx-proxy
    ```

3. Create the required directories and add some sample web content:

    ```bash
    mkdir -p html
    mkdir -p vhost.d
    echo "<h1>Welcome to example.com</h1>" > html/index.html
    ```

4. Start the Docker Compose setup for `website1`:

    ```bash
    docker-compose up -d
    ```

#### Example for `website2`

1. Create a directory for `website2`:

    ```bash
    mkdir -p ../website2
    cd ../website2
    ```

2. Create a `docker-compose.yml` file for `website2` with the following content:

    ```yaml
    version: '3.8'

    services:
      web2:
        image: nginx:latest
        container_name: web2
        environment:
          - VIRTUAL_HOST=example2.com,www.example2.com
          - LETSENCRYPT_HOST=example2.com,www.example2.com
          - LETSENCRYPT_EMAIL=your-email@example.com
        volumes:
          - ./html:/usr/share/nginx/html
          - ./vhost.d:/etc/nginx/conf.d
        networks:
          - nginx-proxy

    networks:
      nginx-proxy:
        external:
          name: nginx-proxy
    ```

3. Create the required directories and add some sample web content:

    ```bash
    mkdir -p html
    mkdir -p vhost.d
    echo "<h1>Welcome to example2.com</h1>" > html/index.html
    ```

4. Start the Docker Compose setup for `website2`:

    ```bash
    docker-compose up -d
    ```

### Summary

1. **Main Setup**: The main Docker Compose file sets up `nginx-proxy` and `letsencrypt-nginx-proxy-companion` services, which handle proxying and SSL certificate management.
2. **Network**: A Docker network named `nginx-proxy` is created and used by all containers to communicate.
3. **Individual Websites**: Each website has its own Docker Compose file in a separate directory. These files define the web services and link them to the `nginx-proxy` network.

By following these steps, you have a scalable and maintainable setup where each website is managed independently, and SSL certificates are automatically provisioned and renewed.
